# Generated by Django 4.2.7 on 2024-05-25 08:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "email_id",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Email ID"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Subject"
                    ),
                ),
                ("body", models.TextField(blank=True, default="", verbose_name="Body")),
                ("sender", models.EmailField(max_length=254, verbose_name="Sender")),
                (
                    "receiver",
                    models.EmailField(max_length=254, verbose_name="Receiver"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Sent at"
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Message ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
            },
        ),
        migrations.CreateModel(
            name="EmailAttachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Filename"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="email_attachments/", verbose_name="File"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="MIME Type"
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="email_reader.email",
                        verbose_name="Email",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Attachment",
                "verbose_name_plural": "Email Attachments",
            },
        ),
    ]
