# Generated by Django 4.2.7 on 2024-06-09 18:30

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("email_reader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator],
                        verbose_name="Email",
                    ),
                ),
                (
                    "is_whitelisted",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="Field used to determine whether the email address is whitelisted for querying via IMAP protocol.",
                        verbose_name="Is Whitelisted",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Address",
                "verbose_name_plural": "Email Addresses",
            },
        ),
        migrations.AlterField(
            model_name="email",
            name="receiver",
            field=models.EmailField(
                max_length=254,
                validators=[django.core.validators.EmailValidator],
                verbose_name="Receiver",
            ),
        ),
        migrations.AlterField(
            model_name="email",
            name="sender",
            field=models.EmailField(
                max_length=254,
                validators=[django.core.validators.EmailValidator],
                verbose_name="Sender",
            ),
        ),
    ]
