# vim: ft=ansible
---

APP_NAME: "email-reader"
WORKER_QUEUE_NAME: [ misc ]

RABBITMQ_IMAGE: rabbitmq
RABBITMQ_TAG: 3.11.13-management

REDIS_IMAGE: redis
REDIS_TAG: 7.0

ENV:
  ALLOWED_HOSTS: "{{ APPLICATION.ALLOWED_HOSTS }}"
  APP_IMAGE: "{{ lookup('env', 'APP_IMAGE') }}"
  CELERY_BROKER: "{{ CELERY_BROKER }}"
  DATABASE_HOST: "{{ APPLICATION.DATABASE_HOST }}"
  DATABASE_NAME: "{{ APPLICATION.DATABASE_NAME }}"
  DATABASE_PASSWORD: "{{ APPLICATION.DATABASE_PASSWORD }}"
  DATABASE_PORT: 5432
  DATABASE_USER: "{{ APPLICATION.DATABASE_USER }}"
  DEBUG: "{{ APPLICATION.DEBUG }}"
  DOCKER_TAG: "{{ lookup('env', 'DOCKER_TAG') }}"
  EMAIL_READER_HOST: "{{ APPLICATION.EMAIL_READER_HOST }}"
  EMAIL_READER_USERNAME: "{{ APPLICATION.EMAIL_READER_USERNAME }}"
  EMAIL_READER_PASSWORD: "{{ APPLICATION.EMAIL_READER_PASSWORD }}"
  ENVIRONMENT: "{{ APPLICATION.ENVIRONMENT }}"
  LOGSTASH_ENABLED: "{{ APPLICATION.LOGSTASH_ENABLED }}"
  LOGSTASH_HOST: "{{ APPLICATION.LOGSTASH_HOST }}"
  LOGSTASH_TAG: "{{ APPLICATION.LOGSTASH_TAG }}"
  RABBITMQ_ERLANG_COOKIE: "{{ APPLICATION.RABBITMQ_ERLANG_COOKIE | default('ERLANG-COOKIE') }}"
  RABBITMQ_HOST: "{{ APPLICATION.RABBITMQ_HOST }}"
  RABBITMQ_MANAGEMENT_PORT: 15672
  RABBITMQ_PASSWORD: "{{ APPLICATION.RABBITMQ_PASSWORD }}"
  RABBITMQ_PORT: "{{ APPLICATION.RABBITMQ_PORT }}"
  RABBITMQ_USERNAME: "{{ APPLICATION.RABBITMQ_USERNAME }}"
  RABBITMQ_VHOST: "{{ APPLICATION.RABBITMQ_VHOST | default('/') }}"
  REDIS_HOST: "{{ APPLICATION.REDIS_HOST }}"
  REDIS_PORT: "{{ APPLICATION.REDIS_PORT }}"
  SECRET_KEY: "{{ APPLICATION.SECRET_KEY }}"
  SENTRY_DSN: "{{ APPLICATION.SENTRY_DSN }}"
  SENTRY_ENABLED: "{{ APPLICATION.SENTRY_ENABLED }}"
  SENTRY_TRACES_SAMPLE_RATE: "{{ APPLICATION.SENTRY_TRACES_SAMPLE_RATE }}"
  SENTRY_PROFILES_SAMPLE_RATE: "{{ APPLICATION.SENTRY_PROFILES_SAMPLE_RATE }}"
  UWSGI_PROCESS: "{{ APPLICATION.UWSGI_PROCESS | default('8') }}"
  VERSION: "{{ lookup('env', 'GIT_HEAD') }}"
  ZOOKEEPER_APP_NAMESPACE: "{{ APPLICATION.ZOOKEEPER_APP_NAMESPACE }}"
  ZOOKEEPER_HOSTS: "{{ APPLICATION.ZOOKEEPER_HOSTS }}"
